name: Notify PR Review

on:
  pull_request:
    branches: [main, dev]
    types: [review_requested, closed]
  issues: 
    types: [opened]
    
jobs:
  notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Notify PR Review
        uses: naver/notify-pr-review@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
            
