name: Camp Daddy CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: 우분투 설치
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      checks: write
      contents: read

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v2

      - name: .env 파일 생성
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle 권한 부여
        run: chmod +x gradlew

      - name: Gradle 빌드 & 테스트 실행
        run: ./gradlew build test